### ISSUE TITLE
Open in Steam Client links

### ISSUE THREAD

**Issue by thakyZ** [SpoonMcForky/remove-trackers#1]
**Base Link:** 
```
steam://openurl/https://steamcommunity.com/.*+
steam://openurl/https://store.steampowered.com/.*+
```
Something that I didn't think of in my own plugin until now:   
Be sure to make it not include links with `linkfilter` in it as it would not only be redundant but possibly used maliciously.
**Link With Trackers:**
```
https://steamcommunity.com/.*+
https://store.steampowered.com/.*+
```

**Comment by SpoonMcForky** [comment]
Closed with 62c25e2117e3201a67908ea92c9c89b73cc8e707
