### ISSUE TITLE
[LINK REQUEST] Reddit

### ISSUE THREAD

**Issue by MicrocontrollersDev** [SpoonMcForky/remove-trackers#2]
**Base Link:** https://www.reddit.com/r/MadeMeSmile/comments/x5l764/how_can_you_not_love_lecturers_that_try_that_much/

**Link With Trackers:** https://www.reddit.com/r/MadeMeSmile/comments/x5l764/how_can_you_not_love_lecturers_that_try_that_much/?utm_source=share&utm_medium=web2x&context=3

Picked the first Reddit post I saw, but it's essentially https://reddit.com/r/[subreddit]/comments/[code]/[title]/[tracker]

Note: slightly different for mobile. For example on iOS, the tracking part is `?utm_source=share&utm_medium=ios_app&utm_name=iossmf`

**Comment by SpoonMcForky** [comment]
Sorry for the delay, only saw this now.
Closed with #[82d7bbb](https://github.com/SpoonMcForky/remove-trackers/commit/82d7bbb428ce3acb6f3c7cba9cfc9a552d06be19)
